###Cloud Build DEMO YAML
options:
  logging: GCS_ONLY # GCS_ONLY, CLOUD_LOGGING_ONLY  ( Default two Options)
steps:
  - id: 'terraform init'
    name: 'hashicorp/terraform:1.3.5'
    entrypoint: sh
    args: ["-c","terraform -chdir=example/ init -upgrade "]
    waitFor:
      - "terraform init"
  - id: 'terraform plan'
    name: 'hashicorp/terraform:1.3.5'
    entrypoint: sh
    args: ["-c","terraform -chdir=example/ plan  -out=plan.out"]  
    waitFor:
      - "terraform plan"
  - id: 'terraform apply'
    name: 'hashicorp/terraform:1.3.5'
    entrypoint: sh
    args: ["-c","terraform -chdir=example/ apply plan.out"]  
    waitFor:
      - "terraform apply"
  # - id: 'tf destroy'
  #   name: 'hashicorp/terraform:1.3.5'
  #   entrypoint: sh
  #   args: ["-c","terraform -chdir=example/ plan -destroy -out=plan.out"]    
  # - id: 'tf destroy plan'
  #   name: 'hashicorp/terraform:1.3.5'
  #   entrypoint: sh
  #   args: ["-c","terraform -chdir=example/ apply plan.out"]   
  # - id: 'startup script with GCE'
  #   name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  #   entrypoint: 'gcloud'
  #   args: ["gcloud"]
