###Cloud Build DEMO YAML
options:
  logging: CLOUD_LOGGING_ONLY # GCS_ONLY, CLOUD_LOGGING_ONLY  ( Default two Options)
steps:
  - id: 'terraform init'
    name: 'hashicorp/terraform:1.3.5'
    entrypoint: sh
    args: ["-c","terraform -chdir=example/ init -upgrade "]
  - id: 'terraform plan'
    name: 'hashicorp/terraform:1.3.5'
    entrypoint: sh
    args: ["-c","terraform -chdir=example/ plan  -out=plan.out"]  
  - name: "gcr.io/cloud-builders/gcloud"
    id: "Create Cloud Build triggers"
    entrypoint: 'bash'
    args:
    - '-eEuo'
    - 'pipefail'
    - '-c'
    - |-
      gcloud components install beta
      gcloud beta builds triggers create github --name="${_TRIGGER_NAME}" --repo-owner="${_REPO_OWNER}" --repo-name="${_REPO_NAME}" --branch-pattern="${_BRANCH_PATTERN}" --build-config="${_BUILD_CONFIG}" --service-account="${_SERVICE_ACCOUNT}" --require-approval --include-logs-with-status
  #   name: 'hashicorp/terraform:1.3.5'
  #   entrypoint: sh
  #   args: ["-c","terraform -chdir=example/ apply plan.out"]  
  # - id: 'tf destroy'
  #   name: 'hashicorp/terraform:1.3.5'
  #   entrypoint: sh
  #   args: ["-c","terraform -chdir=example/ plan -destroy -out=plan.out"]    
  # - id: 'tf destroy plan'
  #   name: 'hashicorp/terraform:1.3.5'
  #   entrypoint: sh
  #   args: ["-c","terraform -chdir=example/ apply plan.out"]   
  # - id: 'startup script with GCE'
  #   name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  #   entrypoint: 'gcloud'
  #   args: ["gcloud"]
substitutions:
  _BRANCH_PATTERN: ^.*
  _REPO_OWNER: JangGyeongSik #armakuni 
  _REPO_NAME: gcp-terraform-cloudbuild-demo
  _TRIGGER_NAME: gcp-terraform-cloud-build-2
  _BUILD_CONFIG: /gcp-terraform-deploy/cloudbuild2.yaml
  _SERVICE_ACCOUNT : projects/gyeongsik-dev/serviceAccounts/gyeongsik-tf-svc@gyeongsik-dev.iam.gserviceaccount.com

    