###CloudBuild2 YAML ### 
options:
  logging: LOGGING_UNSPECIFIED # LOGGING_UNSPECIFIED, NONE, GCS_ONLY, CLOUD_LOGGING_ONLY  ( Default two Options )
steps:
  - id: 'terraform init'
    name: 'hashicorp/terraform:1.3.5'
    entrypoint: sh
    args: ["-c","terraform -chdir=example/ init -upgrade "]
  - id: 'terraform apply'
    name: 'hashicorp/terraform:1.3.5'
    entrypoint: sh
    args: ["-c","terraform -chdir=example/ apply plan.out"]  
  - id: 'tf destroy'
    name: 'hashicorp/terraform:1.3.5'
    entrypoint: sh
    args: ["-c","terraform -chdir=example/ plan -destroy -out=plan.out"]    
  - id: 'tf destroy plan'
    name: 'hashicorp/terraform:1.3.5'
    entrypoint: sh
    args: ["-c","terraform -chdir=example/ apply plan.out"]   
  # - id: 'startup script with GCE'
  #   name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  #   entrypoint: 'gcloud'
  #   args: ["gcloud"]
  # echo "2022-12-21 18:58 PM" >> 

